### ISSUE TITLE
comments: UX improvements

### ISSUE THREAD

**Issue by dalf** [bitem-heg-geneve/ebiodiv-matching-frontend#132]
3 requests about the comments:

- [x] when click on comment on a matcit or speciem, it displays which occ is selected for comment
- [x] click on Send should close the comment
- [x] window comments hide each other:
Scenario:
- click on the comment button from an occ
- click on the comment buttom from another occ
- --> it should hide the previous comment window (currently the window might appear behind the first one)

**Comment by emilie19** [comment]
all requests addressed + comments can be moved: f070015
