### ISSUE TITLE
Bug: don't scroll the filter on the right (position: fixed ?)

### ISSUE THREAD

**Issue by dalf** [bitem-heg-geneve/ebiodiv-matching-frontend#133]
The fields window should not scroll with the table:
![image](https://github.com/bitem-heg-geneve/ebiodiv-matching-frontend/assets/1594191/0518c18d-0627-4f76-afa5-3f359c13c241)

If the user scroll on the right too much, the field window disappear:
![image](https://github.com/bitem-heg-geneve/ebiodiv-matching-frontend/assets/1594191/d70c9ff0-6397-4972-b154-1a8133cfe7d0)

**Comment by emilie19** [comment]
should be solved: 66cec9b
